artists =
  [
    {country: "Afghanistan",
     artist: "farida mahwash",
     url: "http://www.youtube.com/watch?v=KVoXuG03nvc"},
    {country: "Albania",
     artist: "irini qirjako",
     url: "http://www.youtube.com/watch?v=NEQ8dY2cBvw"},
    {country: "Algeria",
     artist: "cheb mami",
     url: "http://www.youtube.com/watch?v=VhjYaeotTYY"},
    {country: "Angola",
     artist: "bonga kwenda",
     url: "http://www.youtube.com/watch?v=connN2YXU_I"},
    {country: "Antarctica",
     artist: "whale noises",
     url: "http://www.youtube.com/watch?v=WabT1L-nN-E"},
    {country: "Argentina",
     artist: "leandro gato barbieri",
     url: "http://www.youtube.com/watch?v=bCqSWIl1sJQ"},
    {country: "Armenia",
     artist: "djivan gasparyan",
     url: "http://www.youtube.com/watch?v=2pvpaCAfUWw"},
    {country: "Australia",
     artist: "slim dusty",
     url: "http://www.youtube.com/watch?v=CwvazMc5EfE"},
    {country: "Austria",
     artist: "a.g. trio",
     url: "http://www.youtube.com/watch?v=Mha6vCSrWQE"},
    {country: "Azerbaijan",
     artist: "aziza mustafa zadeh",
     url: "http://www.youtube.com/watch?v=N4bg-mvJA4k"},
    {country: "Bangladesh",
     artist: "warfaze",
     url: "http://www.youtube.com/watch?v=QHRZYQrDaJc"},
    {country: "Belarus",
     artist: "lyapis trubetskoy",
     url: "http://www.youtube.com/watch?v=nmCKUVPHK7A"},
    {country: "Belgium",
     artist: "django reinhardt",
     url: "http://www.youtube.com/watch?v=VpmOTGungnA"},
    {country: "Belize",
     artist: "andy palacio",
     url: "http://www.youtube.com/watch?v=QZ01Kcx8k6c"},
    {country: "Benin",
     artist: "angelique kidjo",
     url: "http://www.youtube.com/watch?v=duiyobfigfo"},
    {country: "Bhutan",
     artist: "je ngawang gyeltshen",
     url: "http://www.youtube.com/watch?v=DCGJx4sbl2M"},
    {country: "Bolivia",
     artist: "los jairas",
     url: "http://www.youtube.com/watch?v=2X3KXm0rzO8"},
    {country: "Bosnia and Herzegovina",
     artist: "adi lukovac",
     url: "http://www.youtube.com/watch?v=Isk2oWXpzqE"},
    {country: "Botswana",
     artist: "biza mupulu",
     url: "http://www.youtube.com/watch?v=jq1iZoVopJk"},
    {country: "Brazil",
     artist: "antônio carlos jobim",
     url: "http://www.youtube.com/watch?v=Ealy0P7bicQ"},
    {country: "Brunei",
     artist: "nyanyian ramai",
     url: "http://www.youtube.com/watch?v=0dsny-ACkRs"},
    {country: "Bulgaria",
     artist: "le mystère des voix bulgares",
     url: "http://www.youtube.com/watch?v=SD83L4kI3qY"},
    {country: "Burkina Faso",
     artist: "gabin dabiré",
     url: "http://www.youtube.com/watch?v=TV4d_1HjQhs"},
    {country: "Burundi",
     artist: "khadja nin",
     url: "http://www.youtube.com/watch?v=3lpuMD_zJCY"},
    {country: "Cambodia",
     artist: "sinn sisamouth",
     url: "http://www.youtube.com/watch?v=1HF8-sBJ7Ew"},
    {country: "Cameroon",
     artist: "ebanda manfred",
     url: "http://www.youtube.com/watch?v=0Mp3C3tO9qo"},
    {country: "Canada",
     artist: "drake",
     url: "http://www.youtube.com/watch?v=RubBzkZzpUA"},
    {country: "Central African Republic",
     artist: "zokela",
     url: "http://www.youtube.com/watch?v=2z8leocEOms"},
    {country: "Chad",
     artist: "tibesti",
     url: "http://www.youtube.com/watch?v=8uzYWDeNeMQ"},
    {country: "China",
     artist: "yu hongmei",
     url: "http://www.youtube.com/watch?v=9M4gca_uLB4"},
    {country: "Colombia",
     artist: "joe arroyo",
     url: "http://www.youtube.com/watch?v=oWBf9hfW_4Y"},
    {country: "Costa Rica",
     artist: "editus",
     url: "http://www.youtube.com/watch?v=-3xPSWO4Wk8"},
    {country: "Croatia",
     artist: "parni valjak",
     url: "http://www.youtube.com/watch?v=HpEA9DUhCv0"},
    {country: "Cuba",
     artist: "sergio vitier",
     url: "http://www.youtube.com/watch?v=C4d-bZxh60M"},
    {country: "Cyprus",
     artist: "astronomikon",
     url: "http://www.youtube.com/watch?v=f9WAikB11pU"},
    {country: "Czech Republic",
     artist: "poutníci",
     url: "http://www.youtube.com/watch?v=6AvTi74czLk"},
    {country: "Democratic Republic of the Congo",
     artist: "les troubadours du roi baudouin",
     url: "http://www.youtube.com/watch?v=ToNb-02n3KY"},
    {country: "Denmark",
     artist: "aqua",
     url: "http://www.youtube.com/watch?v=ZyhrYis509A"},
    {country: "Djibouti",
     artist: "awale adan",
     url: "http://www.youtube.com/watch?v=leboVNHrhKg"},
    {country: "Dominican Republic",
     artist: "henry santos",
     url: "http://www.youtube.com/watch?v=V8eAZiXEIfQ"},
    {country: "Dominican Republic",
     artist: "henry santos",
     url: "http://www.youtube.com/watch?v=V8eAZiXEIfQ"},
    {country: "East Timor",
     artist: "ego lemos",
     url: "http://www.youtube.com/watch?v=ZkfKR3UUFbE"},
    {country: "Ecuador",
     artist: "huayanay",
     url: "http://www.youtube.com/watch?v=g7SiPZpSp4U"},
    {country: "Egypt",
     artist: "amr diab",
     url: "http://www.youtube.com/watch?v=1j2mLjA2IFk"},
    {country: "El Salvador",
     artist: "pescozada",
     url: "http://www.youtube.com/watch?v=PlANUfyyXGA"},
    {country: "Equatorial Guinea",
     artist: "desmali y su grupo dambo de la costa",
     url: "http://www.youtube.com/watch?v=hUkfKRGxiC0"},
    {country: "Eritrea",
     artist: "bereket mengisteab",
     url: "http://www.youtube.com/watch?v=vegtL1rewQ0"},
    {country: "Estonia",
     artist: "veljo tormis",
     url: "http://www.youtube.com/watch?v=huQ_OcKwGwA"},
    {country: "Ethiopia",
     artist: "alemayehu eshete",
     url: "http://www.youtube.com/watch?v=H1A5NTzSN08"},
    {country: "Falkland Islands",
     artist: "the fighting pig band",
     url: "http://www.youtube.com/watch?v=OTdEqwTJvVs"},
    {country: "Fiji",
     artist: "laisa vulakoro",
     url: "http://www.youtube.com/watch?v=W_bODOSMEn8"},
    {country: "Finland",
     artist: "erkki junkkarinen",
     url: "http://www.youtube.com/watch?v=v3US8s3vC3M"},
    {country: "France",
     artist: "wax tailor",
     url: "http://www.youtube.com/watch?v=fWlFVEfVNxU"},
    {country: "France",
     artist: "wax tailor",
     url: "http://www.youtube.com/watch?v=WEi9ZQrEjr8"},
    {country: "French Southern and Antarctic Lands",
     artist: "whale noises",
     url: "http://www.youtube.com/watch?v=WabT1L-nN-E"},
    {country: "Gabon",
     artist: "patience dabany",
     url: "http://www.youtube.com/watch?v=8XsKk9Aj4MU"},
    {country: "Gambia",
     artist: "foday musa suso",
     url: "http://www.youtube.com/watch?v=f-HLrwAfq4Q"},
    {country: "Georgia",
     artist: "giya kancheli",
     url: "http://www.youtube.com/watch?v=SvYoQisIOJQ"},
    {country: "Germany",
     artist: "rammstein",
     url: "http://www.youtube.com/watch?v=BxroiTRg7Tg"},
    {country: "Ghana",
     artist: "reggie rockstone",
     url: "http://www.youtube.com/watch?v=CUXUZ9gLtjA"},
    {country: "Greece",
     artist: "theodosia tsatsou",
     url: "http://www.youtube.com/watch?v=b1sjRh_NRmQ"},
    {country: "Greenland",
     artist: "siissisoq",
     url: "http://www.youtube.com/watch?v=7glSVDO2LDU&noredirect=1"},
    {country: "Guatemala",
     artist: "ricardo arjona",
     url: "http://www.youtube.com/watch?v=QBju6muDqyU"},
    {country: "Guinea",
     artist: "mory kanté",
     url: "http://www.youtube.com/watch?v=cIUD1Z3pU1g"},
    {country: "Guinea Bissau",
     artist: "super mama djombo",
     url: "http://www.youtube.com/watch?v=vpAD7q5Rlbc"},
    {country: "Guyana",
     artist: "terry gajraj",
     url: "http://www.youtube.com/watch?v=-hk4iNa_3uY"},
    {country: "Haiti",
     artist: "nemours jean baptiste",
     url: "http://www.youtube.com/watch?v=JPME_cIiG-E"},
    {country: "Honduras",
     artist: "diablos negros",
     url: "http://www.youtube.com/watch?v=a7LG3z71O7I"},
    {country: "Hungary",
     artist: "béla bartók",
     url: "http://www.youtube.com/watch?v=szC8cS9M-Ew"},
    {country: "Iceland",
     artist: "björk",
     url: "http://www.youtube.com/watch?v=br2s0xJyFEM"},
    {country: "India",
     artist: "rabbi shergill",
     url: "http://www.youtube.com/watch?v=zBKm2U3rgD8"},
    {country: "Indonesia",
     artist: "fariz rm",
     url: "http://www.youtube.com/watch?v=bVVs8b74tSM"},
    {country: "Iran",
     artist: "deep dish",
     url: "http://www.youtube.com/watch?v=JwCxL4AFqkc"},
    {country: "Iraq",
     artist: "ahmed mukhtar",
     url: "http://www.youtube.com/watch?v=Unlhfztun0c"},
    {country: "Ireland",
     artist: "the cranberries",
     url: "http://www.youtube.com/watch?v=6Ejga4kJUts"},
    {country: "Israel",
     artist: "etti ankri",
     url: "http://www.youtube.com/watch?v=cGbyednPt7E"},
    {country: "Italy",
     artist: "giorgio moroder",
     url: "http://www.youtube.com/watch?v=YT0k99hCY5I"},
    {country: "Ivory Coast",
     artist: "alpha blondy",
     url: "http://www.youtube.com/watch?v=bsoiupLME-w"},
    {country: "Jamaica",
     artist: "bob marley",
     url: "http://www.youtube.com/watch?v=Oo4OnQpwjkc"},
    {country: "Japan",
     artist: "sadao watanabe",
     url: "http://www.youtube.com/watch?v=a_17cbx19cs"},
    {country: "Jordan",
     artist: "omar al-abdallat",
     url: "http://www.youtube.com/watch?v=NnJjVS30zoU"},
    {country: "Kazakhstan",
     artist: "r lizer",
     url: "http://www.youtube.com/watch?v=I-_LYSAvVzU"},
    {country: "Kenya",
     artist: "ken mbatha",
     url: "http://www.youtube.com/watch?v=obshmgb70og"},
    {country: "Kosovo",
     artist: "rita ora",
     url: "http://www.youtube.com/watch?v=dOOxlVUC08Q"},
    {country: "Kuwait",
     artist: "abdallah al rowaished",
     url: "http://www.youtube.com/watch?v=3ymW0V87C9E"},
    {country: "Kyrgyzstan",
     artist: "salamat sadikova",
     url: "http://www.youtube.com/watch?v=MCPdY699HLA"},
    {country: "Laos",
     artist: "vichai koviseth",
     url: "http://www.youtube.com/watch?v=IZFq-mqAhwc"},
    {country: "Latvia",
     artist: "double faced eels",
     url: "http://www.youtube.com/watch?v=-QXMP1r43M8"},
    {country: "Lebanon",
     artist: "nancy ajram",
     url: "http://www.youtube.com/watch?v=8NjZ-xKLGTY"},
    {country: "Lesotho",
     artist: "sankomota",
     url: "http://www.youtube.com/watch?v=5VXUK23RGWM"},
    {country: "Liberia",
     artist: "nimba burr",
     url: "http://www.youtube.com/watch?v=iiiBwjWAqP8"},
    {country: "Libya",
     artist: "ahmed fakroun",
     url: "http://www.youtube.com/watch?v=F7ybdjcC8Qg"},
    {country: "Lithuania",
     artist: "lietuva",
     url: "http://www.youtube.com/watch?v=9hkwOONxNCw"},
    {country: "Luxembourg",
     artist: "gast waltzing",
     url: "http://www.youtube.com/watch?v=qUZm6sEPhyk"},
    {country: "Macedonia",
     artist: "kiril džajkovski",
     url: "http://www.youtube.com/watch?v=izeWkLKMYwI"},
    {country: "Madagascar",
     artist: "nicolas vatomanga",
     url: "http://www.youtube.com/watch?v=xS2ro4QfCiA"},
    {country: "Malawi",
     artist: "wambali mkandawire",
     url: "http://www.youtube.com/watch?v=2zOLaQtxi4c"},
    {country: "Malaysia",
     artist: "siti nurhaliza",
     url: "http://www.youtube.com/watch?v=uyIlczH3Y60"},
    {country: "Mali",
     artist: "oumou sangare",
     url: "http://www.youtube.com/watch?v=Xq9shQQJXdQ"},
    {country: "Mauritania",
     artist: "dimi mint abba",
     url: "http://www.youtube.com/watch?v=Kv7MH7kZf9Q"},
    {country: "Mexico",
     artist: "ritchie valens",
     url: "http://www.youtube.com/watch?v=Jp6j5HJ-Cok"},
    {country: "Moldova",
     artist: "o-zone",
     url: "http://www.youtube.com/watch?v=XArQDnp3T5s"},
    {country: "Mongolia",
     artist: "egshiglen",
     url: "http://www.youtube.com/watch?v=5_XMeoqYwZc"},
    {country: "Montenegro",
     artist: "lepa brena",
     url: "http://www.youtube.com/watch?v=HjgT-hf25R0"},
    {country: "Morocco",
     artist: "amina alaoui",
     url: "http://www.youtube.com/watch?v=pizWG6lAHX4"},
    {country: "Mozambique",
     artist: "fany pfumo",
     url: "http://www.youtube.com/watch?v=OS_8q6W8vhQ"},
    {country: "Myanmar",
     artist: "zay ye",
     url: "http://www.youtube.com/watch?v=WRsycEMk77E"},
    {country: "Namibia",
     artist: "dj kboz",
     url: "http://www.youtube.com/watch?v=Uoug-HYWTQ8"},
    {country: "Nepal",
     artist: "sindhu malla",
     url: "http://www.youtube.com/watch?v=kL0yeOzH1UI"},
    {country: "Netherlands",
     artist: "dj tiësto",
     url: "http://www.youtube.com/watch?v=rMROOGQj5aM"},
    {country: "New Zealand",
     artist: "split enz",
     url: "http://www.youtube.com/watch?v=xv6oOxn1axw"},
    {country: "Nicaragua",
     artist: "giacomo puccini",
     url: "http://www.youtube.com/watch?v=KP3lV-YvCYM"},
    {country: "Niger",
     artist: "kaidan gaskya",
     url: "http://www.youtube.com/watch?v=VgrnVbVI6qQ"},
    {country: "Nigeria",
     artist: "shina peters",
     url: "http://www.youtube.com/watch?v=pwLPKb7zvx4"},
    {country: "North Korea",
     artist: "pochonbo electronic ensemble",
     url: "http://www.youtube.com/watch?v=VtyTeRXB_KM"},
    {country: "Northern Cyprus",
     artist: "babutsa",
     url: "http://www.youtube.com/watch?v=NjTIzXKgsAs"},
    {country: "Norway",
     artist: "blood red throne",
     url: "http://www.youtube.com/watch?v=K6VDT43bLNw"},
    {country: "Oman",
     artist: "salah al-zadjali",
     url: "http://www.youtube.com/watch?v=E6fXUkms8pU"},
    {country: "Pakistan",
     artist: "atif aslam",
     url: "http://www.youtube.com/watch?v=Wno0tlYqJdc"},
    {country: "Panama",
     artist: "lord panama",
     url: "http://www.youtube.com/watch?v=ZqOKPmbUH3I"},
    {country: "Papua New Guinea",
     artist: "o-shen",
     url: "http://www.youtube.com/watch?v=Fpm1tVzOHms"},
    {country: "Paraguay",
     artist: "ripe banana skins",
     url: "http://www.youtube.com/watch?v=PbcE5tDSrh8"},
    {country: "Peru",
     artist: "picaflor de los andes",
     url: "http://www.youtube.com/watch?v=8H2ctjyP8W0"},
    {country: "Philippines",
     artist: "gloc-9",
     url: "http://www.youtube.com/watch?v=5smErKJNceQ"},
    {country: "Poland",
     artist: "chopin",
     url: "http://www.youtube.com/watch?v=YGRO05WcNDk"},
    {country: "Portugal",
     artist: "wraygunn",
     url: "http://www.youtube.com/watch?v=ZkajlywMlsk"},
    {country: "Puerto Rico",
     artist: "menudo",
     url: "http://www.youtube.com/watch?v=qaQ3O444sDM"},
    {country: "Qatar",
     artist: "naser mestarihi",
     url: "http://www.youtube.com/watch?v=bak73MxjXos"},
    {country: "Republic of Serbia",
     artist: "loš zao",
     url: "http://www.youtube.com/watch?v=54HYso7_BWc"},
    {country: "Republic of the Congo",
     artist: "jean serge essous",
     url: "http://www.youtube.com/watch?v=KZw0WLdJfDI"},
    {country: "Romania",
     artist: "akcent",
     url: "http://www.youtube.com/watch?v=ay_fw54W2Fg"},
    {country: "Russia",
     artist: "dima bilan",
     url: "http://www.youtube.com/watch?v=bgLdZuJ2-XA"},
    {country: "Rwanda",
     artist: "the ben meddy",
     url: "http://www.youtube.com/watch?v=_rboTKMG1a0"},
    {country: "Saudi Arabia",
     artist: "talal maddah",
     url: "http://www.youtube.com/watch?v=AXIjNoQTkC8"},
    {country: "Senegal",
     artist: "baaba maal",
     url: "http://www.youtube.com/watch?v=wxumKErHl50"},
    {country: "Sierra Leone",
     artist: "african connexion",
     url: "http://www.youtube.com/watch?v=hL0h52sgsyo"},
    {country: "Slovakia",
     artist: "ján cikker",
     url: "http://www.youtube.com/watch?v=5YKtdeVyt7o"},
    {country: "Slovenia",
     artist: "tomaž svete",
     url: "http://www.youtube.com/watch?v=tOSPXA1dOB0"},
    {country: "Solomon Islands",
     artist: "dakei",
     url: "http://www.youtube.com/watch?v=6Ivrv8JgmUg"},
    {country: "Somalia",
     artist: "aar maanta",
     url: "http://www.youtube.com/watch?v=TDdw3KI1W2Y"},
    {country: "Somaliland",
     artist: "xodeydi",
     url: "http://www.youtube.com/watch?v=yjHxvRM0Lnw"},
    {country: "South Africa",
     artist: "steve hofmeyr",
     url: "http://www.youtube.com/watch?v=BlX8Ktlieo4"},
    {country: "South Korea",
     artist: "psy",
     url: "http://www.youtube.com/watch?v=9bZkp7q19f0"},
    {country: "South Sudan",
     artist: "ayak thiik",
     url: "http://www.youtube.com/watch?v=mgtFREcWi1Y"},
    {country: "Spain",
     artist: "camarón de la isla",
     url: "http://www.youtube.com/watch?v=dIueBl56MV8"},
    {country: "Sudan",
     artist: "shokol rejala",
     url: "http://www.youtube.com/watch?v=XvEzoctFslc"},
    {country: "Suriname",
     artist: "ramdew chaitoe",
     url: "http://www.youtube.com/watch?v=tlecyc_vvi8"},
    {country: "Swaziland",
     artist: "hlengiwe mhlaba",
     url: "http://www.youtube.com/watch?v=brJbrvDqGRk"},
    {country: "Sweden",
     artist: "abba",
     url: "http://www.youtube.com/watch?v=xFrGuyw1V8s"},
    {country: "Switzerland",
     artist: "yves larock",
     url: "http://www.youtube.com/watch?v=zoMYU_nOGNg"},
    {country: "Syria",
     artist: "omar souleyman",
     url: "http://www.youtube.com/watch?v=lVlgMEFu1PI"},
    {country: "Tajikistan",
     artist: "oleg fesov",
     url: "http://www.youtube.com/watch?v=YEH4uaciIKY"},
    {country: "Thailand",
     artist: "pongsit kampee",
     url: "http://www.youtube.com/watch?v=yqzJcrrxWF4"},
    {country: "The Bahamas",
     artist: "alphonso blind blake higgs",
     url: "http://www.youtube.com/watch?v=Kk7I_KWkswQ"},
    {country: "Togo",
     artist: "king mensah",
     url: "http://www.youtube.com/watch?v=5j3Wr09fdIM"},
    {country: "Trinidad and Tobago",
     artist: "ravi b",
     url: "http://www.youtube.com/watch?v=FCazo3PiCBU"},
    {country: "Tunisia",
     artist: "dhafer youssef",
     url: "http://www.youtube.com/watch?v=ePPncJKUoGo"},
    {country: "Turkmenistan",
     artist: "ashkhabad",
     url: "http://www.youtube.com/watch?v=f2ZxUW4SFFE"},
    {country: "United Arab Emirates",
     artist: "the narcicyst",
     url: "http://www.youtube.com/watch?v=0ISHZQJdeSw"},
    {country: "United Kingdom",
     artist: "iron maiden",
     url: "http://www.youtube.com/watch?v=G90ngH2anxQ"},
    {country: "United States of America",
     artist: "nas",
     url: "http://www.youtube.com/watch?v=t5W1GAUwQMs"},
    {country: "Uruguay",
     artist: "alvacast",
     url: "http://www.youtube.com/watch?v=MNsoq7ZjWwU"},
    {country: "Uzbekistan",
     artist: "bolalar",
     url: "http://www.youtube.com/watch?v=9ciANSJoi2U"},
    {country: "Vanuatu",
     artist: "vanessa quai",
     url: "http://www.youtube.com/watch?v=zF8K_Zw1FBc"},
    {country: "Venezuela",
     artist: "ojo fatuo",
     url: "http://www.youtube.com/watch?v=_8TltbduJcM"},
    {country: "Vietnam",
     artist: "my tam",
     url: "http://www.youtube.com/watch?v=GkS-9pOD-0c"},
    {country: "West Bank",
     artist: "ramallah underground",
     url: "http://www.youtube.com/watch?v=A7EtoUO9V-c"},
    {country: "Western Sahara",
     artist: "aziza brahim",
     url: "http://www.youtube.com/watch?v=NbwgshItdEE"},
    {country: "Yemen",
     artist: "ayoob tarish absi",
     url: "http://www.youtube.com/watch?v=1tbgPG2vEi4"},
    {country: "Zambia",
     artist: "shatel",
     url: "http://www.youtube.com/watch?v=aseWtRz4TLk"},
    {country: "Zimbabwe",
     artist: "black umfolosi",
     url: "http://www.youtube.com/watch?v=pQ4Qdjvu68A"}
  ]

artists.each do |artist|
  Country.create(artist)
end
